---
title: ''
csl: mbio.csl
fontsize: 11pt
output:
  pdf_document:
    includes:
      in_header: header.tex
    keep_tex: yes
geometry: margin=0.75in
bibliography: null
---
\pagenumbering{gobble}
```{r knitr_settings, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE}

source('../code/functions.R')

loadLibs(c("tidyverse", "scales", "knitr", "rmarkdown", "stringr"))

```


**Table S1: Breakdown of select genes and corresponding KEGG ID analyzed.**
```{r supplemental_table1, echo=FALSE, message=FALSE, warning=FALSE}

Kegg_ID <- c("K00929", "K01034", "K01035", "K01908", "K01895", "K00932", "K19697", 
             "K18372", "K00467", "K00156", "K00925", "K01512", "K01067", "K18118", "K01026", 
             "K01905", "K22224", "K01895", "K00128", "K14085", "K00149", "K00138")

Gene_Name <- c("Butyrate Kinase", "Acetate CoA subnunit A", "Acetate CoA subunit B", "Propionyl-CoA Synthetase", 
               "Acetyl-CoA Synthetase", "Propionate Kinase", "Propionate Kinase", "Methyl Acetate Hydrolase", 
               "Lactate 2-Monooxygenase", "Pyruvate Dehydrogenase", "Acetate Kinase", "Acylphosphatase", 
               "Acetyl-CoA Hydrolase", "Succinyl-CoA:Acetate", "Propionate CoA-Transferase", 
               "Acetate---CoA Ligase subunit A", "Acetate---CoA Ligase subunit B", "Acetyl-CoA Synthetase", 
               "Aldehyde Dehydrogenase", "Aldehyde Dehydrogenase Family 7", "Aldehyde Dehydrogenase Family 9", 
               "Aldehyde Dehydrogenase")

sup_table1 <- data_frame(Kegg_ID, Gene_Name)

colnames(sup_table1) <-  c("KEGG IDs", "Gene Name")


kable(sup_table1, format = "markdown", align = 'c', padding = 2)


```

\newpage

**Table S2: Breakdown of Kruskal-Wallis tests using PICRUSt imputed relative abundance of select genes in SCFA pathways.**
```{r supplemental_table2, echo=FALSE, message=FALSE, warning=FALSE}
table_s2 <- read_csv("../data/process/specific_scfa_kruskal_picrust_summary.csv") %>% 
  select(kegg_ortholog, statistic, p.value, bh) %>% 
  mutate_at(vars(statistic:bh), function(x) round(x, digits = 3))

colnames(table_s2) <-  c("KEGG IDs", "Rank Sum Statistic", "P-value", "BH")

kable(table_s2, format = "markdown", align = 'c', padding = 2)
# opf_select <- read_csv("../data/process/select_scfa_opf_kruskal_summary.csv")
```


\newpage

**Table S3: Breakdown of Kruskal-Wallis tests using counts per million from metagenomic sequencing of select genes in SCFA pathways.**
```{r supplemental_table3, echo=FALSE, message=FALSE, warning=FALSE}
table_s3 <- read_csv("../data/process/select_scfa_opf_kruskal_summary.csv") %>% 
  select(kegg_id, statistic, p.value, bh) %>% 
  mutate_at(vars(statistic:bh), function(x) round(x, digits = 3))

colnames(table_s3) <-  c("KEGG IDs", "Rank Sum Statistic", "P-value", "BH")

kable(table_s3, format = "markdown", align = 'c', padding = 2)
```




